spring.application.name=resume-analyzer

#database
spring.datasource.url=jdbc:postgresql://localhost:5432/resume_analyzer
spring.datasource.username=postgres
spring.datasource.password=${DB_Password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Security
jwt.secret=##386427myResumeAnalyserProjectSecretKey##@@@!@oweiyr98237ehqwkdhuiowegfbjdbqewgyfamsdb$$%%293749023740
jwt.expiration=86400000000